name: Update readme files

on:
  push:
    paths:
      - 'problems/**'
      - 'scripts/update_readme.py'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: README updates
      run: |
        python scripts/update_readme.py
        python scripts/generate_problem_readmes.py

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "[BOT] Update README files" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Haotin00/leetcode-diary.git HEAD:master
