name: Update readme file

on:
  push:
    paths:
      - 'problems/**'
      - 'scripts/update_readme.py'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run update_readme.py
      run: |
        python scripts/update_readme.py

    - name: Commit changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "Update problem count in README" || echo "No changes to commit"
        git push https://x-access-token:"$GH_PAT"@github.com/Haotin00/leetcode-diary.git HEAD:master
